development:
  adapter: postgresql
  encoding: unicode
  database: transparental-soluations_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: transparental-soluations_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: transparental-soluations_production
  pool: 5
  username: postgres
  password: postgres
